recipe: default.v1

assistant_id: tri-nhan

language: vi

pipeline:
  - name: vietnamese_tokenizer.VietnameseTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.7

policies:
